{'06/25/2020, 22:24:07': SpotifyException(400, -1, 'https://api.spotify.com/v1/tracks/2MLHyLyp7momlgw:\n invalid id')}
{'06/25/2020, 22:24:40': NameError("name 'find_closest_neighbors' is not defined")}
{'06/25/2020, 22:25:44': TypeError("'NoneType' object is not iterable")}
{'06/25/2020, 22:26:30': TypeError("'NoneType' object is not iterable")}
{'06/25/2020, 22:26:50': TypeError('string indices must be integers')}
{'06/25/2020, 22:29:02': TypeError('string indices must be integers')}
{'06/25/2020, 22:31:32': TypeError('string indices must be integers')}
{'06/25/2020, 22:33:25': TypeError('string indices must be integers')}
{'06/25/2020, 22:35:06': TypeError("'<' not supported between instances of 'dict' and 'str'")}
{'06/25/2020, 22:36:09': TypeError("'<' not supported between instances of 'int' and 'str'")}
{'06/25/2020, 22:37:02': KeyError('songid')}
{'06/25/2020, 22:39:52': TypeError('Object of type dict_values is not JSON serializable')}
{'06/25/2020, 22:41:08': TypeError("unhashable type: 'dict'")}
{'06/25/2020, 22:52:21': TypeError('Object of type dict_values is not JSON serializable')}
{'06/25/2020, 23:38:24': TypeError('Object of type dict_values is not JSON serializable')}
{'06/25/2020, 23:40:41': TypeError('Object of type ObjectId is not JSON serializable')}
{'06/25/2020, 23:41:33': TypeError('Object of type ObjectId is not JSON serializable')}
{'06/25/2020, 23:43:45': TypeError('Object of type ObjectId is not JSON serializable')}
{'06/25/2020, 23:45:45': TypeError('Object of type ObjectId is not JSON serializable')}
{'06/25/2020, 23:55:03': TypeError('Object of type ObjectId is not JSON serializable')}
{'06/26/2020, 00:01:13': JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 3 (char 2)')}
{'06/26/2020, 00:03:00': TypeError('Object of type ObjectId is not JSON serializable')}
{'07/06/2020, 20:55:59': TypeError('Object of type ObjectId is not JSON serializable')}
{'07/06/2020, 20:56:54': TypeError('Object of type dict_values is not JSON serializable')}
{'07/06/2020, 20:58:45': TypeError('Object of type ObjectId is not JSON serializable')}
{'07/06/2020, 21:00:21': TypeError('Object of type ObjectId is not JSON serializable')}
{'07/06/2020, 21:01:15': TypeError('Object of type ObjectId is not JSON serializable')}
{'07/06/2020, 21:02:30': TypeError('Object of type dict_values is not JSON serializable')}
{'07/06/2020, 21:04:22': TypeError('Object of type dict_values is not JSON serializable')}
{'07/06/2020, 21:05:40': TypeError('Object of type dict_values is not JSON serializable')}
{'07/06/2020, 21:23:16': SpotifyException(404, -1, 'https://api.spotify.com/v1/tracks/45LIS5vxDcdMniZcD6biUD:\n non existing id')}
{'07/06/2020, 21:25:38': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:26:23': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:27:31': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:29:52': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:31:31': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:33:30': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:34:47': AttributeError("'Prediction_Model' object has no attribute 'scaler'")}
{'07/06/2020, 21:37:12': ValueError('in user code:\n\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1147 predict_function  *\n        outputs = self.distribute_strategy.run(\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:951 run  **\n        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2290 call_for_each_replica\n        return self._call_for_each_replica(fn, args, kwargs)\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2649 _call_for_each_replica\n        return fn(*args, **kwargs)\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\training.py:1122 predict_step  **\n        return self(x, training=False)\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:927 __call__\n        outputs = call_fn(cast_inputs, *args, **kwargs)\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\network.py:717 call\n        return self._run_internal_graph(\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\network.py:888 _run_internal_graph\n        output_tensors = layer(computed_tensors, **kwargs)\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\base_layer.py:885 __call__\n        input_spec.assert_input_compatibility(self.input_spec, inputs,\n    c:\\users\\mauli\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\tensorflow\\python\\keras\\engine\\input_spec.py:212 assert_input_compatibility\n        raise ValueError(\n\n    ValueError: Input 0 of layer dense is incompatible with the layer: expected axis -1 of input shape to have value 13 but received input with shape [None, 12]\n')}
{'07/06/2020, 21:41:37': ValueError('operands could not be broadcast together with shapes (1,13) (12,) (1,13) ')}
{'07/06/2020, 21:42:52': ValueError('operands could not be broadcast together with shapes (1,13) (12,) (1,13) ')}
{'07/06/2020, 21:49:55': InvalidDocument("cannot encode object: array([3.4851277, 3.050659 ], dtype=float32), of type: <class 'numpy.ndarray'>")}
{'07/06/2020, 21:50:47': InvalidDocument("cannot encode object: array([3.4851277, 3.050659 ], dtype=float32), of type: <class 'numpy.ndarray'>")}
{'07/06/2020, 21:52:26': InvalidDocument("cannot encode object: 3.4851277, of type: <class 'numpy.float32'>")}
{'07/06/2020, 21:54:04': KeyError('songid')}
{'07/06/2020, 21:56:39': TypeError('Object of type dict_values is not JSON serializable')}
